export const routes = {
  home: "/",
  learn: "/learn",
  login: "/login",
  account: "/account",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  traineeDashboard: "/dashboard/trainee",
  organizationDashboard: "/dashboard/organization",
  learningHub: "/learning-hub",
  organizations: "/organizations",
  about: "/about",
  download: "/download",
  rag: "/demo/rag",
  adminOverview: "/admin/overview",
  adminAccounts: "/admin/accounts",
  adminOrganizations: "/admin/organizations",
  adminReviews: "/admin/reviews",
  adminLearn: "/admin/learn",
  adminLibrary: "/admin/library",
  adminCommerce: "/admin/commerce",
  adminSupport: "/admin/support",
  workspaceBuildings: "/workspace/buildings",
  workspaceBilling: "/workspace/billing",
  workspaceBillingReturn: "/workspace/billing/return",
  workspaceIfc: "/workspace/ifc",
  workspaceSupport: "/workspace/support",
  workspaceProfile: "/workspace/profile",
} as const;

export type RouteKey = keyof typeof routes;
